### ISSUE TITLE
Incorrect interpolation?

### ISSUE THREAD

**Issue by siefkenj** [alesgenova/pitch-detection#12]
I'm not exactly sure what this function is supposed to do, but it will give incorrect quadratic interpolations, since it doesn't use `left.x` or `right.x`...

https://github.com/alesgenova/pitch-detection/blob/09a0ee6eb35bbd77ebb8168bafb740f64678ed97/src/utils/peak.rs#L84-L94

Is that on purpose?

**Comment by alesgenova** [comment]
Fixed by #13
