### ISSUE TITLE
LICENCE or similar file is missing

### ISSUE THREAD

**Issue by eras** [alesgenova/pitch-detection#18]
It would be nice to have such a file, even if the license is mentioned in `Cargo.toml`. GitHub can also detect the license via that.

**Comment by codetheweb** [comment]
Would love a license as well. :)

**Comment by mattkanwisher** [comment]
bump on this, we would love to integrate this

**Comment by alesgenova** [comment]
Sorry, unforgivable delay in getting this done.
I'm traveling today, I'll try to add a license file tomorrow

**Comment by alesgenova** [comment]
Finally added the MIT license file. PR merged into master
